from representations import convertDNAToOneHot, addChannels, getOneHotGenome
from slicing import getFunctionOnRegions, getFunctionOnPositions, sliceGenomeArray
from pwm import convolveGenome, getPositionWeightMatrix